### ISSUE TITLE
Añadir enlace a las fotografías

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#24]
Pinchar en las fotos debería llevar a las URI originales de Commons.

**Comment by olea** [comment]
Las URL canónicas para las imágenes son bastante feas para la gente normal:

- https://commons.wikimedia.org/wiki/File:20141025_Shockwave_Truck_Alliance_Air_Show_2014-3.jpg
- https://commons.m.wikimedia.org/wiki/File:20141025_Shockwave_Truck_Alliance_Air_Show_2014-3.jpg

Sin embargo se puede usar un «mediaviewer» mucho más resultón:

- https://commons.wikimedia.org/wiki/File:20141025_Shockwave_Truck_Alliance_Air_Show_2014-3.jpg#/media/File:20141025_Shockwave_Truck_Alliance_Air_Show_2014-3.jpg

Como puede verse la estructura de la URL sería:
- https://commons.wikimedia.org/wiki/File:IMAGEN.jpg#/media/File:IMAGEN.jpg

Para representar la página no sé qué preferís, si abrirla dentro de la misma caja HTML de la aplicación o externamente en el navegador del sistema. Yo no tengo más preferencia que la comodidad del usuario.

**Comment by PabloBerrettoni** [comment]
@olea Puedes confirmar que este issue ya a sido resuelto para cerrarlo?

**Comment by olea** [comment]
@PabloBerrettoni En este momento no lo veo resuelto ni en cicerone.g ni en wikilocal.p.es.

Estoy de viaje y no puedo verificarlo en una instancia local.

**Comment by gnaomi0** [comment]
Hi,@olea! Please can you check the changes by @facuzero and confirms if this issue has been solved?
