### ISSUE TITLE
Problema con el recorte de imágenes

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#25]
En las fotos en vertical con frecuencia los recortes no son reconocibles o útiles.

Se propone usar la misma técnica de Instagram y otros en las que se rellena el resto del espacio con un fondo que es la versión ampliada muy borrosa de la imagen.

**Comment by facuzero** [comment]
@olea Es necesario utilizar el filtro de instagram?

**Comment by olea** [comment]
> @olea Es necesario utilizar el filtro de instagram?

A lo que me refiero no es técnicamente a un filtro de imagen, sino a la técnica que usa Instagram para llenar en horizontal el espacio que dejaría libre una imagen vertical. Yo no soy experto y en realidad me daría igual la técnica mientras el resultado visual sea aceptable.

**Comment by olea** [comment]
Closing as https://github.com/PukaraES/Cicerone/pull/60.
