### ISSUE TITLE
Problema de usabilidad con la paginación

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#26]
[Pantalla principal] -> [paginación del listado de bienes]: el número que aparece en el medio no tiene sentido, o no se puede interpretar bien o es redundante con el marcador de la numeración de la página, que puede desaparecer si la cantidad de páginas es grande.

**Comment by olea** [comment]
Por ejemplo, cuando visito mi ciudad (Almería):

![Captura desde 2022-08-09 09-50-12](https://user-images.githubusercontent.com/141267/183595452-f51b3bf6-b827-4c63-be43-b3286d54fa06.png)

**Comment by GonzaEnrique27** [comment]
@olea la logica de la paginacion es llegar hasta la 4ta y no mostrar las paginas siguientes hasta las ultimas 4 paginas... o sea, que de la 13 a la 16 (en tu caso) son las ultimas paginas con resultados... el 1 que esta en medio muestra en que pagina te encontras... mi pregunta es, como rediseñamos esto?

**Comment by GonzaEnrique27** [comment]
![image](https://user-images.githubusercontent.com/90418763/183666127-acf279ee-707a-4cf9-956f-d146f705d953.png)

**Comment by GonzaEnrique27** [comment]
ahi deje el "actual page" debajo de la paginacion... entonces cuando vas avanzando de pagina te marca en que pagina estas

**Comment by olea** [comment]
> ahi deje el "actual page" debajo de la paginacion... entonces cuando vas avanzando de pagina te marca en que pagina estas

Tiene buena pinta.  No puedo probarlo porque la aplicación no carga en este momento.

**Comment by olea** [comment]
La UX no es uniforme. Cuando llegas a un ubicación: 

![Screenshot_20220810-084121](https://user-images.githubusercontent.com/141267/183834018-5594a566-13e9-4eeb-827e-cfec5e1e9422.png)

Y parecería que no va a haber más bienes. Pero al pinchar en página siguiente:

![Screenshot_20220810-084130](https://user-images.githubusercontent.com/141267/183834110-d06e3a84-dc25-40b7-a7da-c1f900e1265e.png)

El interfaz debe comportarse de manera congruente.

**Comment by olea** [comment]
Al avanzar en la paginación a veces se descompone la barra de paginación:

![Screenshot_20220810-085928](https://user-images.githubusercontent.com/141267/183836152-9048dea1-d4f1-48bf-ad9a-0d4edb930b0f.png)

**Comment by PabloBerrettoni** [comment]
@olea Solucione los problemas que mencionaste en este PR:
https://github.com/PukaraES/Cicerone/pull/76

**Comment by olea** [comment]
La exploración de bienes no funciona, el cambio de vistas tampoco, el avance en la paginación tampoco. ¿Será que la rama acarrea cambios defectuosos?

**Comment by PabloBerrettoni** [comment]
Issue resuelto.
