### ISSUE TITLE
Retroceder pierde el estado anterior

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#27]
Problema al navegar en la aplicación (retroceder): a entrar en un bien y retroceder a la vista principal (da igual si con el botón [Atrás] de la aplicación o con las funciones del navegador, se pierde el estado tanto de las coordenadas del mapa (si las has cambiado, claro) como de la posición en el paginado.

No debería ocurrir.

**Comment by PabloBerrettoni** [comment]
@olea I made a PR with the fixes that were requested here

**Comment by olea** [comment]
I've not extensively checked, but the behavior seems enhanced 👍

Would be great to design a set of test cases to check, like navigation combinations to validate the patch. Sadly I don't have time now to help with this.
