### ISSUE TITLE
Defectos en los extractos de Wikipedia

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#28]
Las descripciones de Wikipedia:
	En la ficha del bien:
	- deberían filtrar las referencias ([1..n])
	- deberían añadir un enlace «para saber más» o «artículo principal» apuntando al respectivo artículo Wikipedia.

**Comment by PabloBerrettoni** [comment]
@olea No entendí lo de las referencias que comentas deberíamos filtrar. Eso esta relacionado a lo ya hecho en el [issue#31](https://github.com/PukaraES/Cicerone/issues/31) ?
Y como querrías que agreguemos el enlace al articulo original de wikipedia, tienes alguna idea en cuanto a lo estetico?

**Comment by olea** [comment]
@PabloBerrettoni Las referencias en un artículo de Wikipedia son los códigos en corchetes que al ser pinchados en el texto muestran las referencias que respaldan tal o cual afirmación:

![Captura desde 2022-08-09 09-38-14](https://user-images.githubusercontent.com/141267/183592483-8f0904c2-544c-44b7-8ea0-ea592713e3a3.png)

Como Cicerone no muestra los textos completos, las referencias tampoco deben aparecer.

**Comment by olea** [comment]
> Y como querrías que agreguemos el enlace al articulo original de wikipedia, tienes alguna idea en cuanto a lo estetico?

No tengo ninguna idea preconcebida. Algo justo al acabar el texto, por ejemplo: «Enlace a Wikipedia», con el enlace al artículo en cuestión. Pero ni entiendo de diseño gráfico ni de usabilidad :-)

**Comment by PabloBerrettoni** [comment]
This has been fixed with this PR: https://github.com/PukaraES/Cicerone/pull/57
@olea Can you confirm that's all so that we can close the issue?

**Comment by olea** [comment]
> @olea Can you confirm that's all so that we can close the issue?

As far as I'm checking, this problem happens anymore.
