### ISSUE TITLE
No deben aparecer bienes duplicados

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#29]
Cuando un bien tiene dos coordenadas geográficas aparece duplicado en el listado. No debería ocurrir pero hay muchísimos casos. Ha de modificarse la consulta SPARQL para usar sólo la mejor coordenada.

**Comment by olea** [comment]
Vale, parece que ya sé cómo se arregla. Hay que usar SAMPLE.

**Comment by olea** [comment]
@PabloBerrettoni por favor: cópiame aquí cada una de las consultas sparql que estamos usando y yo te devuelvo cada una eliminando el duplicado de coordenadas (P625).

**Comment by eddymdz** [comment]
@PabloBerrettoni puedes contestar a las solicitudes de @olea ?

**Comment by olea** [comment]
Como le contaba ayer a Gonzalo la búsqueda principal creo que ahora debemos usar es https://github.com/PukaraES/Cicerone/issues/40#issuecomment-1193208185 

Usando SAMPLE y  wikibase:directClaim filtramos ¿todos? los casos duplicados acarreados desde el estado de los elementos en Wikidata sin tener que añadir lógica de nuestro lado.

**Comment by olea** [comment]
Hasta donde comprendo a esa consulta le sobrarían cosas:

* redundante porque ya se ha definido el idioma en el otro SERVICE:
             _SERVICE wikibase:label {
              bd:serviceParam wikibase:language 'es'.
              ?place schema:description ?placeDescription. }_
* innecesario _SAMPLE(?placeDescription) AS ?placeDescription)_ porque nunca vamos a tener más de una descripción por lengua
* entiendo que si estamos haciendo una aplicación geolocalizada las coordenadas nunca deben ser opcionales, ergo  _OPTIONAL { ?place wdt:P625 ?coord. }_ debe ser realmente _?place wdt:P625 ?coord._

```
const query = `SELECT ?place ?placeLabel ?dist (SAMPLE(?country) AS ?country) (SAMPLE(?image) AS ?image) (SAMPLE(?coord) AS ?coord) 
          WHERE {
            SERVICE wikibase:around {
              ?place wdt:P625 ?location.
              bd:serviceParam wikibase:center 'Point(${this.longitude} ${this.latitude})'^^geo:wktLiteral.
              bd:serviceParam wikibase:radius '30'. }
            SERVICE wikibase:label {
              bd:serviceParam wikibase:language 'es'.}
            ?place wdt:P1435 ?monument.
            OPTIONAL { ?place wdt:P18 ?image. }
            OPTIONAL { ?place wdt:P17 ?country. }
            ?place wdt:P625 ?coord. 
            BIND(geof:distance('Point(${this.longitude} ${this.latitude})'^^geo:wktLiteral, ?location) as ?dist)
          }
          GROUP BY ?place ?placeLabel ?dist ?placeDescription
          ORDER BY ?dist`
```

Conceptualmente esta consulta no devuelve _places_ sino bienes (cosas, ítemes). Al hablar de un «place» nos referiríamos a un lugar, a la ubicación donde está situada «la cosa». En la práctica da igual pero durante el desarrollo la conversación puede ser ambigua.

**Comment by olea** [comment]
Ésta creo que debería ser la consulta definitiva para monumentos:

```

SELECT DISTINCT ?place ?placeLabel ?dist  (SAMPLE(?country) AS ?country) (SAMPLE(?P625) AS ?P625) (SAMPLE(?image) AS ?image) WHERE {
            SERVICE wikibase:around {
              ?place wdt:P625 ?location.
              bd:serviceParam wikibase:center 'Point(${this.longitude} ${this.latitude})'^^geo:wktLiteral.
              bd:serviceParam wikibase:radius '10'. }
  {
    {
      SELECT DISTINCT ?prop WHERE {
        {
          ?propi (wdt:P31/(wdt:P279*)) wd:Q43831109;
            wikibase:directClaim ?prop.
        }
        UNION
        {
          ?propi (wdt:P31/(wdt:P279*)) wd:Q62589316;
            wikibase:directClaim ?prop.
        }
      }
    }
    ?place ?prop ?foo.
  }
  UNION
  { ?place wdt:P1435 ?foo. }
  FILTER NOT EXISTS {?place wdt:P576 ?bar.}
  FILTER NOT EXISTS {?place wdt:P582 ?bar.}
  OPTIONAL { ?place wdt:P18 ?image. }
  OPTIONAL { ?place wdt:P17 ?country. }
  ?place wdt:P625 ?P625.
  BIND(geof:distance(?lugar, ?location) AS ?dist)

  SERVICE wikibase:label { bd:serviceParam wikibase:language "es". }
}
GROUP BY ?place ?placeLabel ?dist
ORDER BY (?dist)
``` 

He reducido el radio de búsqueda a 10 Km porque 30 me parecen demasiados. Sólo en Almería me lista 300 elementos. Imáginate en cualquier capital de país.

La versión equivalente funcional en WDQS: https://w.wiki/5WAp

**Comment by olea** [comment]
Ahora que me doy cuenta:

> const query = `SELECT ?place ?placeLabel ?dist (SAMPLE(?country) AS ?country) (SAMPLE(?image) AS ?image) (SAMPLE(?coord) AS ?coord) (SAMPLE(?placeDescription) AS ?placeDescription)

Si ya estábamos usando SAMPLE, ¿por qué nos salían esos duplicados? Sé que tienen que ver con imágenes y coordenadas porque cuando he corregido los elementos el duplicado desaparecía de Cicerone .

**Comment by PabloBerrettoni** [comment]
@olea Intenté usar la 'consulta definitiva' y me salta un error al leer el valor de coord en distintos lugares de la app. Estuve viendo y detecte que falta el sample de coord en el select y falta tambien la segunda consulta de coord en wikilabel. Lo que logre hacer fue que no me salte mas el error cargue la pagina pero sin datos por un error 500 al hacer la consulta.

**Comment by olea** [comment]
@PabloBerrettoni a ver si es porque en una se usa la variable _?coord_ y en otra, en cambio, _?P625_. Si fuera sólo esto entiendo que debería bastar con usar el nombre correcto.

**Comment by PabloBerrettoni** [comment]
@olea Cambiando eso la consulta funciono pero solo trae ciudades. Era esa la idea?
![image](https://user-images.githubusercontent.com/78081626/182649213-66264675-6d4d-41b5-829f-91688b1de691.png)

**Comment by olea** [comment]
Bueno, después de las respectivas videoconferencias con @GonzaEnrique27 y @PabloBerrettoni creo que podemos concluir que lo que se pretende hacer por este lado (#29) es lo que ya ha avanzado Gonzalo relacionado con #40. Entiendo pues que la vista de entrada de la aplicación, la inicial, sería como lo que Gonzalo tiene entre manos, mostrando tres vistas de las respectivas consultas:

1. monumentos https://github.com/PukaraES/Cicerone/issues/40#issuecomment-1193208185
2. espacios naturales https://github.com/PukaraES/Cicerone/issues/40#issue-1315378182
3. y https://github.com/PukaraES/Cicerone/issues/40#issuecomment-1192901386, que no sé ni cómo llamarla (¿«otros»?)

La predeterminada entiendo que debería ser la primera, variante de la que creo que hasta ahora hemos estado llamando «consulta principal».

Creo que procede cerrar este boletín. Para cualquier duda, por favor, preguntadme sin dilación.
