### ISSUE TITLE
Datos a mostrar en la ficha del bien

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#31]
La ficha debería representar:

- Primero: usar la Descripción del elemento WD
- El resumen de la Wikipedia en el idioma del usuario
  - Todos los enlaces a Sitelinks que estén disponibles en el idioma del usuario, en particular:
     - la correspondiente a wikipedia, por la lengua de la sesión de usuario
     - ídem con el correspondiente a wikivoyage
  - mapa con la situación del bien
  - y alguna indicación (o enlace) de cómo llegar al bien

Propiedades WD: 

- Las mismas que Monumental
- pero si no están disponibles no pintarlas en blanco ni dejar huecos

Imágenes potencialmente disponibles:

- PXXX <- propiedad Wikidata incluida en la ficha descargada
- ordenadas por prioridad

1. P4291, vista panorámica <- candidata a imagen principal de la ficha  (usar sólo una imagen o sólo la primera disponible)
2. P18, imagen <- si no hay P4291 ésta será la imagen principal (usar sólo una imagen o sólo la primera disponible)
3. P5775, imagen de interior  (usar sólo una imagen o sólo la primera disponible)
4. P373, categoría en Commons (a veces es redundante con el sitelink a Commons)
5. sitelink a Commons (a veces es redundante con P373)
6. P935, galería en Commons 
7. P5252, vista invernal  (usar sólo una imagen o sólo la primera disponible)
8. P3451, vista nocturna  (usar sólo una imagen o sólo la primera disponible)
9. P8517, vista desde el elemento  (usar sólo una imagen o sólo la primera disponible)
10. P10, vídeo  (usar sólo una imagen o sólo la primera disponible)
11. P4640, foto esférica  (usar sólo una imagen o sólo la primera disponible)

Lo más complicado creo que es cómo extraer imágenes ilustrativas desde las colecciones servidas a través de:

- P373, categoría en Commons (a veces es redundante con el sitelink a Commons)
- sitelink a Commons (a veces es redundante con P373)
- P935, galería en Commons 

y hay que tener en cuenta que:

- En teoría todo lo que esté en la galería de Commons está incluido en la categoría. 
- Las galerías no son muy frecuentes, pero a veces las hay y son interesantes. Si existe, extrayendo las imágenes que incluye estaríamos servidos. De hecho sería la mejor práctica de organización de multimedia en Commons.
- El caso entre P373/sitelink Commons es algo particular: en realidad en cualquier caso el valor debe ser el mismo en uno que en otro. Si existe la P373 listo, si no, entonces se busca el sitelink a Commons.
- En cuanto a Commons, ahora mismo la aplicación extrae imágenes pero hay casos donde no hay imágenes en la categoría principal sino en las subcategorías.

La verdad es que ahora que lo reflexiono probablemente lo más práctico sea:
- si hay un valor de  P373/sitelink Commons entonces usarlo como un enlace a «más imágenes» o algo muy parecido
- buscar la galería P935 y de allí extraemos las imágenes extra con las que ilustraremos la ficha, o al menos usar las n-primeras (¿4? ¿5? ¿10?)
- tiene todo el sentido del mundo que la selección de imágenes de más calidad se haga a través de las galerías porque el resto puede ser un maremagnun en cuanto a la calidad de las fotos.

Aparte, algo que podría postergarse son las imágenes esféricas y los vídeos. Para las imágenes esféricas está disponible un visor JS. Es una pijotada muy chula, pero no es imperativa.

**Comment by PabloBerrettoni** [comment]
Hi @olea we are already working on some of the features requested here and some of the others are currently in the backlog. I'll be adding these requests to the user history of the feature and close this issue.

**Comment by PabloBerrettoni** [comment]
@olea Estuve consultando e investigando como obtener la informacion requerida y no logro llegar a obtener la informacion desde una query. En el codigo de monumental localizamos una url donde traen informacion e imagenes desde una url pero no podemos saber cual es dado que no hemos sido capaces tampoco de levantar el servidor.
```
var uploader = vm.uploader = new FileUploader({
    url: `${$window.__env.baseUrl}/commons`,
    // url: 'https://commons.wikimedia.org/w/api.php',
    withCredentials: true,
  });
```

**Comment by olea** [comment]
Para extraer los datos de una ficha no hace falta ninguna query. Una vez que sabes el id del elemento en cuestión sólo hay que usar alguna de las exportaciones predeterminadas. Por ejemplo, para Q5637104:

```
<link rel="alternate" href="https://www.wikidata.org/wiki/Special:EntityData/Q5637104.json" type="application/json"/>
<link rel="alternate" href="https://www.wikidata.org/wiki/Special:EntityData/Q5637104.php" type="application/vnd.php.serialized"/>
<link rel="alternate" href="https://www.wikidata.org/wiki/Special:EntityData/Q5637104.n3" type="text/n3"/>
<link rel="alternate" href="https://www.wikidata.org/wiki/Special:EntityData/Q5637104.ttl" type="text/turtle"/>
<link rel="alternate" href="https://www.wikidata.org/wiki/Special:EntityData/Q5637104.nt" type="application/n-triples"/>
<link rel="alternate" href="https://www.wikidata.org/wiki/Special:EntityData/Q5637104.rdf" type="application/rdf+xml"/>
<link rel="alternate" href="https://www.wikidata.org/wiki/Special:EntityData/Q5637104.jsonld" type="application/ld+json"/>
```

Los enlaces están empotrados en el código HTML de la página del elemento WD. Y el esquema de la URI es siempre el mismo. Es trivial cargar el json, por ejemplo, del elemento en cuestión y extraer los valores de las propiedades que nos interesan.

Lo del _uploader_ probablemente es para subir imágenes, que está completamente fuera de nuestros objetivos.

**Comment by eddymdz** [comment]
@PabloBerrettoni tal como comenta @olea efectivamente no requieres realizar una query para obtener los datos de las propiedades. Por ejemplo para una entidad con este código, puedes obtener las propiedades de esta forma:

`const entitiesResponse = await fetch(`https://www.wikidata.org/w/api.php?action=wbgetentities&format=json&ids=${this.getId}&props=info|labels|claims&origin=*`)`

Chequea mi implementación parcial acá:[https://github.com/PukaraES/Cicerone/commit/adb74426751666679e20cab8b15637d680b165d5](https://github.com/PukaraES/Cicerone/commit/adb74426751666679e20cab8b15637d680b165d5)

**Comment by olea** [comment]
La verdad es que hasta que hoy no me puse  mirar la API de Wikidata no
tenía ni idea de las cosas que se podían hacer con ellas.

**Comment by PabloBerrettoni** [comment]
@eddymdz @olea Acá esta implementada la lógica para obtener la informacion de los monumentos: 
[Link a la rama con el avance del issue.](https://github.com/PukaraES/Cicerone/tree/CICERONE-ISSUES-31)
Le falta los estilos que voy a estar agregando ahora pero quería confirmar que les parezca bien la implementacion.

**Comment by eddymdz** [comment]
@olea estos datos ya se encuentran disponible en producción, entiendo que se podrá ir mejorando y agregando más datos. Voy a cerrar el issue pero sin con la implementación consideras que en términos de la información no está completo, por favor ábrelo nuevamente. 

![screenshot-cicerone guide-2022 08 06-15_36_54](https://user-images.githubusercontent.com/31184671/183251306-a56b4003-2b17-4132-9965-e27ac3658530.png)
