### ISSUE TITLE
Fallo al representar imágenes

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#33]
Al entrar al bien la aplicación no es capaz de manejar las subcategorías de Commons, lo que es un problema cuando no hay fotos en la categoría principal.

**Comment by PabloBerrettoni** [comment]
@olea A que te refieres con esto? Tienes algun ejemplo?

**Comment by PabloBerrettoni** [comment]
@olea Puedes confirmar si es que el error persiste? Porque creo que a sido tratado en un PR de manera secundaria

**Comment by olea** [comment]
No he sabido ni reproducirlo ni verificarlo.

Cierro por aquí y volveremos a abrirlo de ser necesario.
