### ISSUE TITLE
La ficha no muestra las fotos

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#34]
Por algún motivo esta ficha no representa fotos que están disponibles: https://wikilocal.pukara.es/places/Q97286273/place-details

Tal vez esté relacionado con el uso (o no) de las propiedades de imágenes mencionadas en #31 .

**Comment by eddymdz** [comment]
@PabloBerrettoni @njrzr ustedes están dándole seguimiento a esto?

**Comment by PabloBerrettoni** [comment]
Si, estamos teniendo en cuenta todos los issues

**Comment by PabloBerrettoni** [comment]
@olea Este issue ya a sido resuelto, puedes confirmarlo?

**Comment by olea** [comment]
@PabloBerrettoni puedo confirmar que sí :-)
