### ISSUE TITLE
Readme build instructions doesn't work

### ISSUE THREAD

**Issue by olea** [PukaraES/Cicerone#67]
There is nothing about using nodejs 14.8.0, etc.

**Comment by PabloBerrettoni** [comment]
@olea This case is being managed in this PR. Do you think the way we declare that node version 14.x is needed is ok? Or would you want us to change it?

**Comment by olea** [comment]
It should be detailed all the configuration procedure and the hard requirements like that.  Also, if has been dockerized, how to set it up.

Just as you'd expect for another software out there.

**Comment by gnaomi0** [comment]
@olea Can we close the issue?

**Comment by gnaomi0** [comment]
@olea I edited the readme. Can you confirm if it's okay?

**Comment by olea** [comment]
I don't have the time to check it, sorry :-/ 

But it's easy to verify: just follow all the instructions from a clean state to see if works or not.
